name: Deploy Hugo Site via Nix

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Mount Determinate Nix Engine
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Render Site Layout via Nix Package Build
        run: nix build .#

      - name: Upload Static Content Package
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Straight to GitHub Pages Live Hosting
        id: deployment
        uses: actions/deploy-pages@v4
